### ISSUE TITLE
<details> tag not rendering properly in kramdown

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/til#1]
#### Description
right now I am using the `jekyll-theme-hacker` theme.
The markdown on README is correctly rendering but not on the github pages website.
I used the [following](https://docs.github.com/en/enterprise/2.14/user/articles/setting-up-your-github-pages-site-locally-with-jekyll) guide to set up the theme locally but its rendering the same result.

```yml
title: til - Bhupesh Varshney
description: Today I Learned - Interesting things I learn every day related to software development, computer science & stuff.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM% 
```

#### Version
- Ruby `ruby 2.5.1p57 (2018-03-29 revision 63029)`
- Jekyll `jekyll 3.8.7`
